<a href="https://colab.research.google.com/github/setyo-dwi-pratama/FGA-DTS-KOMINFO/blob/main/pertemuan13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import pandas as pd
import numpy as np

In [98]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'

In [99]:
df = pd.read_csv(url, header=None)
df.head()

   0    1            2    3    4     5   ...    20   21    22  23  24     25
0   3    ?  alfa-romero  gas  std   two  ...   9.0  111  5000  21  27  13495
1   3    ?  alfa-romero  gas  std   two  ...   9.0  111  5000  21  27  16500
2   1    ?  alfa-romero  gas  std   two  ...   9.0  154  5000  19  26  16500
3   2  164         audi  gas  std  four  ...  10.0  102  5500  24  30  13950
4   2  164         audi  gas  std  four  ...   8.0  115  5500  18  22  17450

[5 rows x 26 columns]

In [100]:
headers = ['symboling','normalized-losses','make','fuel-type','aspiration','num-of-doors','body-style',
           'drive-wheels','engine-location','wheel-base','length','width','height','curb-weight','engine-type',
           'num-of-cylinders','engine-size','fuel-system','bore','stroke','compression-ratio','horspower','peak-rpm',
           'city-mpg','highway-mpg','price']

In [101]:
df.columns=headers
df.head()

   symboling normalized-losses         make  ... city-mpg highway-mpg  price
0          3                 ?  alfa-romero  ...       21          27  13495
1          3                 ?  alfa-romero  ...       21          27  16500
2          1                 ?  alfa-romero  ...       19          26  16500
3          2               164         audi  ...       24          30  13950
4          2               164         audi  ...       18          22  17450

[5 rows x 26 columns]

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horspower          205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [103]:
df['normalized-losses'].value_counts()

?      41
161    11
91      8
150     7
134     6
128     6
104     6
65      5
102     5
85      5
94      5
74      5
95      5
168     5
103     5
122     4
148     4
118     4
93      4
106     4
154     3
137     3
115     3
83      3
125     3
101     3
158     2
129     2
119     2
87      2
192     2
110     2
108     2
164     2
194     2
89      2
188     2
197     2
145     2
81      2
153     2
113     2
98      1
107     1
90      1
186     1
142     1
77      1
78      1
256     1
231     1
121     1
Name: normalized-losses, dtype: int64

In [104]:
df['normalized-losses'] = df['normalized-losses'].str.replace('?','0')

In [105]:
df['normalized-losses'] = df['normalized-losses'].astype(int)

In [106]:
rata = df['normalized-losses'].mean()

In [107]:
rata

97.6

In [112]:
df['normalized-losses'] = df['normalized-losses'].replace(0, rata)

In [113]:
df

     symboling  normalized-losses         make  ... city-mpg highway-mpg  price
0            3               97.6  alfa-romero  ...       21          27  13495
1            3               97.6  alfa-romero  ...       21          27  16500
2            1               97.6  alfa-romero  ...       19          26  16500
3            2              164.0         audi  ...       24          30  13950
4            2              164.0         audi  ...       18          22  17450
..         ...                ...          ...  ...      ...         ...    ...
200         -1               95.0        volvo  ...       23          28  16845
201         -1               95.0        volvo  ...       19          25  19045
202         -1               95.0        volvo  ...       18          23  21485
203         -1               95.0        volvo  ...       26          27  22470
204         -1               95.0        volvo  ...       19          25  22625

[205 rows x 26 columns]

In [114]:
df['normalized-losses'].value_counts()

97.6     41
161.0    11
91.0      8
150.0     7
134.0     6
104.0     6
128.0     6
103.0     5
65.0      5
94.0      5
102.0     5
74.0      5
85.0      5
95.0      5
168.0     5
106.0     4
118.0     4
148.0     4
122.0     4
93.0      4
137.0     3
125.0     3
115.0     3
154.0     3
101.0     3
83.0      3
188.0     2
145.0     2
158.0     2
113.0     2
110.0     2
81.0      2
192.0     2
153.0     2
129.0     2
194.0     2
197.0     2
87.0      2
119.0     2
89.0      2
108.0     2
164.0     2
231.0     1
78.0      1
186.0     1
107.0     1
77.0      1
98.0      1
121.0     1
142.0     1
90.0      1
256.0     1
Name: normalized-losses, dtype: int64